### ISSUE TITLE
[DevReport] Bakeperms command doesn't work

### ISSUE THREAD

**Issue by Josh-65** [ToberoCat/ImprovedFactions_new#49]
I'm dev build 3 bake perms has this error in console when running it.

[12:26:49 WARN]: java.io.FileNotFoundException: plugins\ImprovedFactions\.temp\baked-permissions.yml (The system cannot find the path specified)
[12:26:49 WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[12:26:49 WARN]:        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[12:26:49 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[12:26:49 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[12:26:49 WARN]:        at ImprovedFactions.Spigot-2.0.0-dev.3.jar//com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createGenerator(YAMLFactory.java:448)
[12:26:49 WARN]:        at ImprovedFactions.Spigot-2.0.0-dev.3.jar//com.fasterxml.jackson.databind.ObjectMapper.createGenerator(ObjectMapper.java:1203)
[12:26:49 WARN]:        at ImprovedFactions.Spigot-2.0.0-dev.3.jar//com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3763)
[12:26:49 WARN]:        at ImprovedFactions.Spigot-2.0.0-dev.3.jar//io.github.toberocat.improvedFactions.core.utils.PermissionFileTool.bakeToFile(PermissionFileTool.java:35)
[12:26:49 WARN]:        at ImprovedFactions.Spigot-2.0.0-dev.3.jar//io.github.toberocat.improvedFactions.core.command.sub.utils.BakePermissionsCommand.run(BakePermissionsCommand.java:45)
[12:26:49 WARN]:        at ImprovedFactions.Spigot-2.0.0-dev.3.jar//io.github.toberocat.improvedfactions.spigot.command.component.SpigotCommandHandler.executeCommandChain(SpigotCommandHandler.java:74)
[12:26:49 WARN]:        at ImprovedFactions.Spigot-2.0.0-dev.3.jar//io.github.toberocat.improvedfactions.spigot.command.SpigotFactionCommand.onCommand(SpigotFactionCommand.java:32)
[12:26:49 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:26:49 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:26:49 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[12:26:49 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2307)
[12:26:49 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2118)
[12:26:49 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2099)
[12:26:49 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:26:49 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:26:49 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[12:26:49 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:26:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:26:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[12:26:49 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1400)
[12:26:49 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[12:26:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[12:26:49 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1377)
[12:26:49 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1370)
[12:26:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:26:49 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1348)
[12:26:49 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1230)
[12:26:49 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[12:26:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ToberoCat** [comment]
This command is a dev only one. It creates a file with all permissions, so I don't have to do it

**Comment by Josh-65** [comment]
Should properly be hidden from the autocomplete or tell the user that its dev only when ran.

**Comment by ToberoCat** [comment]
Yeah, I'll hide it
