### ISSUE TITLE
[DevReport] `/f gui translate` doesn't work

### ISSUE THREAD

**Issue by Josh-65** [ToberoCat/ImprovedFactions_new#52]
In game it show that there was an internal error. The console shows
```
[17:04:37 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin ImprovedFactions v2.0.0-dev.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2307) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2118) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2099) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "map" is null
        at io.github.toberocat.improvedFactions.core.command.sub.gui.ItemTranslatableCommand.lambda$createFromArgs$1(ItemTranslatableCommand.java:66) ~[ImprovedFactions.Spigot-2.0.0-dev.4.jar:?]
        at java.util.function.Function.lambda$andThen$1(Function.java:88) ~[?:?]
        at io.github.toberocat.improvedFactions.core.translator.Translation.getMessage(Translation.java:77) ~[ImprovedFactions.Spigot-2.0.0-dev.4.jar:?]
        at io.github.toberocat.improvedfactions.spigot.player.SpigotFactionPlayer.getMessage(SpigotFactionPlayer.java:44) ~[ImprovedFactions.Spigot-2.0.0-dev.4.jar:?]
        at io.github.toberocat.improvedfactions.spigot.player.SpigotFactionPlayer.sendTranslatable(SpigotFactionPlayer.java:124) ~[ImprovedFactions.Spigot-2.0.0-dev.4.jar:?]
        at io.github.toberocat.improvedFactions.core.command.sub.gui.ItemTranslatableCommand.createFromArgs(ItemTranslatableCommand.java:66) ~[ImprovedFactions.Spigot-2.0.0-dev.4.jar:?]
        at io.github.toberocat.improvedFactions.core.command.sub.gui.ItemTranslatableCommand.createFromArgs(ItemTranslatableCommand.java:19) ~[ImprovedFactions.Spigot-2.0.0-dev.4.jar:?]
        at io.github.toberocat.improvedfactions.spigot.command.component.SpigotCommandHandler.runCommand(SpigotCommandHandler.java:67) ~[ImprovedFactions.Spigot-2.0.0-dev.4.jar:?]
        at io.github.toberocat.improvedfactions.spigot.command.component.SpigotCommandHandler.executeCommandChain(SpigotCommandHandler.java:57) ~[ImprovedFactions.Spigot-2.0.0-dev.4.jar:?]
        at io.github.toberocat.improvedfactions.spigot.command.SpigotFactionCommand.onCommand(SpigotFactionCommand.java:32) ~[ImprovedFactions.Spigot-2.0.0-dev.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more
```

**Comment by ToberoCat** [comment]
Have you hold an item and used /f gui translate <name> or did it appear because of the missing error message?

**Comment by Josh-65** [comment]
I wasn't holding an item when running it. What do you mean missing error message?

**Comment by ToberoCat** [comment]
I probably just forgot to add a section <translate>....</translate> into the en_us.xml. That's why it can't find the path to the error message, leading to this error

**Comment by Josh-65** [comment]
I presume this command isn't a thing anymore.
