### ISSUE TITLE
[Bug] Plugin doesn't work when server is stopped and restarted

### ISSUE THREAD

**Issue by Lead-Lord** [ToberoCat/ImprovedFactions_new#75]
**Describe the bug**

**[15:44:50 INFO]: [GuiEngineAPI] Took 7ms rendering to a virtual player background
[15:44:50 INFO]: [GuiEngineAPI] Took in total 19ms to get background displayed to the virtual player
[15:44:50 INFO]: [GuiEngineAPI] Validating manage-faction.gui
[15:44:50 WARN]: io.github.toberocat.guiengine.api.exception.GuiIORuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character '{' (code 123) in prolog; expected '<'
[15:44:50 WARN]:  at [row,col {unknown-source}]: [1,1]
[15:44:50 WARN]:        at 1. 팩션 API (GuiEngineAPI-1.0.0).jar//io.github.toberocat.guiengine.api.GuiEngineApi.loadXmlGui(GuiEngineApi.java:135)
[15:44:50 WARN]:        at 1. 팩션 API (GuiEngineAPI-1.0.0).jar//io.github.toberocat.guiengine.api.GuiEngineApi.validateGui(GuiEngineApi.java:204)
[15:44:50 WARN]:        at 1. 팩션 API (GuiEngineAPI-1.0.0).jar//io.github.toberocat.guiengine.api.GuiEngineApi.reload(GuiEngineApi.java:106)
[15:44:50 WARN]:        at 0. 팩션 테스트 (ImprovedFactions_Paper-2.0.0-dev.5).jar//io.github.toberocat.improvedfactions.spigot.handler.GuiApi.<init>(GuiApi.java:18)
[15:44:50 WARN]:        at 0. 팩션 테스트 (ImprovedFactions_Paper-2.0.0-dev.5).jar//io.github.toberocat.improvedfactions.spigot.plugin.ImprovedImplementation.<init>(ImprovedImplementation.java:47)
[15:44:50 WARN]:        at 0. 팩션 테스트 (ImprovedFactions_Paper-2.0.0-dev.5).jar//io.github.toberocat.improvedfactions.spigot.MainIF.registerHandlers(MainIF.java:79)
[15:44:50 WARN]:        at 0. 팩션 테스트 (ImprovedFactions_Paper-2.0.0-dev.5).jar//io.github.toberocat.improvedfactions.spigot.MainIF.onEnable(MainIF.java:31)
[15:44:50 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[15:44:50 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[15:44:50 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[15:44:50 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[15:44:50 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:556)
[15:44:50 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:467)
[15:44:50 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640)
[15:44:50 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439)
[15:44:50 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:310)
[15:44:50 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106)
[15:44:50 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[15:44:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[15:44:50 WARN]: Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character '{' (code 123) in prolog; expected '<'
[15:44:50 WARN]:  at [row,col {unknown-source}]: [1,1]
[15:44:50 WARN]:        at 1. 팩션 API (GuiEngineAPI-1.0.0).jar//com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:734)
[15:44:50 WARN]:        at 1. 팩션 API (GuiEngineAPI-1.0.0).jar//com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:618)
[15:44:50 WARN]:        at 1. 팩션 API (GuiEngineAPI-1.0.0).jar//com.fasterxml.jackson.dataformat.xml.XmlFactory.createParser(XmlFactory.java:496)
[15:44:50 WARN]:        at 1. 팩션 API (GuiEngineAPI-1.0.0).jar//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
[15:44:50 WARN]:        at 1. 팩션 API (GuiEngineAPI-1.0.0).jar//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
[15:44:50 WARN]:        at 1. 팩션 API (GuiEngineAPI-1.0.0).jar//io.github.toberocat.guiengine.api.GuiEngineApi.loadXmlGui(GuiEngineApi.java:133)
[15:44:50 WARN]:        ... 18 more
[15:44:50 WARN]: Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '{' (code 123) in prolog; expected '<'
[15:44:50 WARN]:  at [row,col {unknown-source}]: [1,1]
[15:44:50 WARN]:        at 1. 팩션 API (GuiEngineAPI-1.0.0).jar//com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:666)
[15:44:50 WARN]:        at 1. 팩션 API (GuiEngineAPI-1.0.0).jar//com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2148)
[15:44:50 WARN]:        at 1. 팩션 API (GuiEngineAPI-1.0.0).jar//com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1180)
[15:44:50 WARN]:        at 1. 팩션 API (GuiEngineAPI-1.0.0).jar//com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:729)
[15:44:50 WARN]:        ... 23 more
[15:44:50 ERROR]: [GuiEngine] The gui couldn't get rendered to an virtual player. Please take a look at it
[15:44:50 ERROR]: Error occurred while enabling ImprovedFactions v2.0.0-dev.5 (Is it up to date?)
io.github.toberocat.guiengine.api.exception.GuiIORuntimeException: io.github.toberocat.guiengine.api.exception.GuiIORuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character '{' (code 123) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
        at io.github.toberocat.guiengine.api.GuiEngineApi.validateGui(GuiEngineApi.java:255) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at io.github.toberocat.guiengine.api.GuiEngineApi.reload(GuiEngineApi.java:106) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at io.github.toberocat.improvedfactions.spigot.handler.GuiApi.<init>(GuiApi.java:18) ~[0. 팩션 테스트 (ImprovedFactions_Paper-2.0.0-dev.5).jar:?]
        at io.github.toberocat.improvedfactions.spigot.plugin.ImprovedImplementation.<init>(ImprovedImplementation.java:47) ~[0. 팩션 테스트 (ImprovedFactions_Paper-2.0.0-dev.5).jar:?]
        at io.github.toberocat.improvedfactions.spigot.MainIF.registerHandlers(MainIF.java:79) ~[0. 팩션 테스트 (ImprovedFactions_Paper-2.0.0-dev.5).jar:?]
        at io.github.toberocat.improvedfactions.spigot.MainIF.onEnable(MainIF.java:31) ~[0. 팩션 테스트 (ImprovedFactions_Paper-2.0.0-dev.5).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[pufferfish-1.19.4.jar:git-Pufferfish-70]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.19.4.jar:git-Pufferfish-70]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:556) ~[pufferfish-1.19.4.jar:git-Pufferfish-70]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:467) ~[pufferfish-1.19.4.jar:git-Pufferfish-70]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[pufferfish-1.19.4.jar:git-Pufferfish-70]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[pufferfish-1.19.4.jar:git-Pufferfish-70]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.19.4.jar:git-Pufferfish-70]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1106) ~[pufferfish-1.19.4.jar:git-Pufferfish-70]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[pufferfish-1.19.4.jar:git-Pufferfish-70]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.github.toberocat.guiengine.api.exception.GuiIORuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character '{' (code 123) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
        at io.github.toberocat.guiengine.api.GuiEngineApi.loadXmlGui(GuiEngineApi.java:135) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at io.github.toberocat.guiengine.api.GuiEngineApi.validateGui(GuiEngineApi.java:204) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        ... 17 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character '{' (code 123) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:734) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:618) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory.createParser(XmlFactory.java:496) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at io.github.toberocat.guiengine.api.GuiEngineApi.loadXmlGui(GuiEngineApi.java:133) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at io.github.toberocat.guiengine.api.GuiEngineApi.validateGui(GuiEngineApi.java:204) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        ... 17 more
Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '{' (code 123) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
        at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:666) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2148) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1180) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:729) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:618) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory.createParser(XmlFactory.java:496) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at io.github.toberocat.guiengine.api.GuiEngineApi.loadXmlGui(GuiEngineApi.java:133) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        at io.github.toberocat.guiengine.api.GuiEngineApi.validateGui(GuiEngineApi.java:204) ~[1. 팩션 API (GuiEngineAPI-1.0.0).jar:?]
        ... 17 more
[15:44:50 INFO]: [ImprovedFactions] Disabling ImprovedFactions v2.0.0-dev.5**

**To Reproduce**
1. "Stop and restart the server"

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Plugin: ImprovedFactions_Paper-2.0.0-dev.5, GuiEngineAPI-1.0.0, ToberoCore-1.0.0
 - Server: 1.19.4

**Additional context**

**Comment by Lead-Lord** [comment]
If I delete the plugin's "ImprovedFactions" file and run it again, it works fine.
However, the plug-in is disabled just by turning the server off and on without making any modifications.

**Comment by Lead-Lord** [comment]
If I delete the plugin's "ImprovedFactions" file and run it again, it works fine.
However, the plug-in is disabled just by turning the server off and on without making any modifications.

**Comment by ToberoCat** [comment]
Thank you for reporting. It looks like the plugin created a gui file that shouldn't be in the gui folder.
For it to work, you must delete the manage-faction.gui file. It's in an old format.

Should be fixed the a newer dev build

**Comment by Josh65-2201** [comment]
This has been fixed in the new v2 stable from discord by the way

**Comment by ToberoCat** [comment]
Fixed with v2 and new gui version
